name: stock_api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - requests=2.31.0
  - pandas=2.1.4
  - numpy=1.24.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - pip=23.2.1
  - pip:
    - python-dotenv==1.0.0
    - yfinance==0.2.18
    - alpha-vantage==2.3.1
    - plotly==5.15.0
    - streamlit==1.25.0